- preview/Win7Msix/Win7MSIXInstaller/PackageInfo.cpp
- preview/Win7Msix/Win7MSIXInstaller/PackageInfo.hpp
- preview/Win7Msix/Win7MSIXInstaller/StartMenuLink.cpp
- preview/Win7Msix/Win7MSIXInstaller/StartMenuLink.hpp
Classic Win32 applications (out of Desktop Bridge) have to declare the Application User Model ID (AUMID) on the app's shortcut in Start in order to enable toast notifications. 
The diff will automatically assign the `Application Model User Id` of the .msix installed by `win7msixInstaller`.
>  Automatically assign AppUserModelId to the shortcut created by win7msixinstaller to enable desktop toast notifications on Win8+

- preview/Win7Msix/Win7MSIXInstaller/Win7MSIXInstaller.vcxproj
We were not able to compile the current .vcproj because of the broken paths for `AppxPackaging.hpp` and `MSIXWindows.hpp`
Add also support of the following configurations:
- Debug/x86
- Release/x86
- Debug/x64
in addition to Release/x64.
> Fix paths in Win7MSIXInstaller.vcproj + support Debug and x86

- preview/Win7Msix/Win7MSIXInstaller/FilePaths.cpp
- preview/Win7Msix/Win7MSIXInstaller/GeneralUtil.hpp
strings returned by `SHGetKnownFolderPath` are allocated using `CoTaskMemAlloc`, therefore they shouldn't be freed using `std::free`, it would corrupt the heap and crash the app. We should use `CoTaskMemFree` instead.
Documentation:
> The calling process is responsible for freeing this resource once it is no longer needed by calling CoTaskMemFree.
https://docs.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath
> Fix heap corruption in win7 msix installer

- preview/Win7Msix/Win7MSIXInstaller/RegistryDevirtualizer.cpp
By default, `TOKEN_PRIVILEGES` can only host 1 `LUID_AND_ATTRIBUTES`, but Win7MsixInstaller writes 2 of them, overwriting the 12 following bytes.
See documentation:
> Important  The constant ANYSIZE_ARRAY is defined as 1 in the public header Winnt.h. To create this array with more than one element, you must allocate sufficient memory for the structure to take into account additional elements.
https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_token_privileges
> Fix memory corruption due to TOKEN_PRIVILEGES not allocating enough memory

- preview/Win7Msix/Win7MSIXInstaller/InstallUI.cpp
Not sure if it was by design, but in case it wasn't, here is a small diff to remove the gray background of the checkbox.
**Before:**
**After:**
> [Win7MsixInstaller] Make the background of the checkbox transparent

- README.md
- pipelines/azure-pipelines-macos.yml
- test/MacOS-Linux/MacOS-Linux-Etc.sh
Build release and debug macOS binaries using Azure Pipelines. Builds are executed automatically for every PR to master and when PRs are completed to master.
Also fix bad merge in MacOS-Linux-Etc.sh. We were running twice the bundle tests
> Setup macOS pipelines

- preview/Win7Msix/Win7MSIXInstaller/InstallUI.cpp
- preview/Win7Msix/Win7MSIXInstaller/InstallUI.hpp
The title, description as well as the application logo were never redraw when the window was partially out of the screen or after being minimized.
The fix splits `DisplayPackageInfo` into 2 parts:
- `LoadInfo`: called only one time, extracting application name, publisher name, version number and logo and caching them to improve performance.
- `DrawPackageInfo, called when the window receives the event `WM_PAINT`, redrawing textblocks and the logo
+ Load the progress bar only when we will display it.
**Before:**
**Fixed:**
> [Win7MsixInstaller] Fix UI drawing when the dialog is minimized or partially out of the screen.

- preview/Win7Msix/.editorconfig
- preview/Win7Msix/Win7MSIXInstaller.sln
This project uses space indentations, we should override global VS settings so every contributors will use spaces when they work on win7msixinstaller.
> Add .editorconfig to override VS settings to use spaces to indent

- preview/Win7Msix/Win7MSIXInstaller/InstallUI.cpp
We should not force the color of the textblock to black, instead, we should use the WINDOWS_TEXT color to make the win7msixInstaller accessible (high-contrast support)
**Before:**
**After:**
(High-contrast #1)
(High-contrast Black)
(high-contrast #2)
> [Win7MsixInstaller] Support High Contrasts for accessibility

- src/msix/PAL/XML/AOSP/XmlObject.cpp
Running our BVTs targeting a newer android emulator fail. This is due to an unnecessary call to ReleaseByteArrayElements() while parsing any xml using the inbox java parser. 
ReleaseByteArrayElements() should only be called with a corresponding GetByteArrayElements(). [See Release<PrimitiveType>ArrayElements doc](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#Release_PrimitiveType_ArrayElements_routines)
Using SetByteArrayRegion and deleting the local reference (via JObjectDeleter) should be sufficient.
Repro: ./testasoponmac.sh -c "system-images;android-26;google_apis;x86" -i
> Android BVTs failing for newer android systems.

- preview/Win7Msix/Win7MSIXInstaller/MsixRequest.cpp
- preview/Win7Msix/Win7MSIXInstaller/PopulatePackageInfo.cpp
On running, Win7msixInstaller.exe -FindPackage (packagefullname), if the package is not installed on the machine, it currently returns, 'Failed to process request 80070490'. Modifying this to return, 'Package not found'.
> FindPackage returns 'Package not found' error

- CMakeLists.txt
- cmake/ios.cmake
The Azure Hosted MacOS machines just updated to CMake 3.14. This version warns if the CACHE type is not recognize for the set command producing:
```
CMake Warning (dev) at cmake/ios.cmake:28 (set):
implicitly converting 'string' to 'STRING' type.
```
See [this ](https://gitlab.kitware.com/cmake/cmake/merge_requests/2874/diffs) for the CMake change that produces this warning.
Also, adding CMake version to the log for better diagnosability.
> Fix CMake's set CACHE type on the ios toolchain

- pipelines/azure-pipelines-aosp.yml
- pipelines/azure-pipelines-ios.yml
- pipelines/azure-pipelines-linux.yml
- pipelines/azure-pipelines-macos.yml
- pipelines/azure-pipelines-windows.yml
Adding exclude paths for files that don't affect the MSIX SDK and add release_v* branches as triggers.
This way we make sure to don't build the Win7Installer preview or any non-code affecting PRs.
> Improve pipelines

- preview/Win7Msix/Win7MSIXInstaller/InstallUI.cpp
Fix a little issue due a previous PR: display the version number of the package in the dialog.
> Show the version number of the package in the UI

- pipelines/azure-pipelines-aosp.yml
- pipelines/azure-pipelines-ios.yml
- pipelines/azure-pipelines-linux.yml
- pipelines/azure-pipelines-macos.yml
- pipelines/azure-pipelines-windows.yml
A build will not start if any of the files in the exclude list is in a PR, even if the change contains a file that is not on the exclude list.
We don't want that, instead we should do the builds if any of the MSIX SDK files are present.
> Add include path files, instead of exclude, to azure pipelines definitions

- src/inc/AppxPackageWriter.hpp
- src/inc/DirectoryObject.hpp
- src/inc/MsixErrors.hpp
- src/inc/ScopeExit.hpp
- src/msix/CMakeLists.txt
- src/msix/PAL/FileSystem/POSIX/DirectoryObject.cpp
- src/msix/PAL/FileSystem/Win32/DirectoryObject.cpp
- src/msix/common/AppxFactory.cpp
- src/msix/msix.cpp
- src/msix/pack/AppxPackageWriter.cpp
- src/msix/unpack/AppxPackageObject.cpp
1. AppxPackageWriter class that will produce the package.
2. Add ScopeExit.hpp to help deleting a file when some error ocurred while producing a file. It can also be used for more purposes.
AppxPackageWriter implements an internal interfaces that will Pack given an IDirectoryObject. This will be only used for the PackPackage entrypoint. Eventually, Pack, AddPayloadFile and AddPayloadsFile will call the same writer internal methods. 
Next will be an xmlwriter to start producing the blockmap and content type files.
> PackageWriter skeleton

- preview/Win7Msix/Win7MSIXInstallerLib/PackageManager.cpp
I'm not the most familiar with lambdas, it does look like the lambda capture doesn't capture as i'd expect and that this is crashing because processRequest is called with no MsixRequest class.
Working around the issue for now by explicitly passing the msixRequest pointer as a parameter to the lambda, which verified works with the UI and installs work as expected.
> Fix crash when ui used

- preview/MsixCore/MsixCoreInstaller/RegistryDevirtualizer.cpp
- preview/MsixCore/MsixCoreInstaller/RegistryKey.cpp
- preview/MsixCore/Tests/test.ps1
2. do not write nullptr for REG_SZ, instead give it an empty null-terminated string
3. change test to use scilexer.dll instead of nppshell_06.dll which is sometimes stuck in use by explorer.exe and can't be rewritten.
Jyothi noticed that the notepadplus.msix after installed, attempting to launch by right clicking a text file and selecting "Edit in Notepad++" gives an unexpected dialog. This is due to the registry devirtualization writing an nullptr as part of a REG_SZ type. Instead, we should write a null-terminated string.
Also, after launching Notepad++ this way, our automated test for this package fails in re-install because nppshell_06.dll is held in use by explorer.exe. So, we choose a separate versioned DLL (scilexer) instead.
> 1. Do not write REG_NONE into registry. default to REG_SZ

- preview/MsixCore/MsixCoreInstaller/RegistryKey.cpp
Follow-up fix to pass in the correct size to RegSetValueEx in BYTES instead of WCHARs.
> setvalue takes size in bytes, not wchars

- src/inc/DirectoryObject.hpp
- src/msix/AppxPackageObject.cpp
makemsix.exe unbundle -d <output> -p <bundle> -pfn AVs because we try to access the appx manifest from the AppxPackageObject instead of the appx bundle manifest. 
The expected behavior is using the pfn option in a bundle should be:
```
<output directory>\
<bundle package family name>\
AppxBlockMap.xml
AppxMetadata\AppxBundleManifest.xml
<package family name 1>\
<package family name n>\
```
> Fix AV for unbundle using pfn option

- preview/MsixCore/MsixCoreInstaller/ValidateTargetDeviceFamily.cpp
- preview/MsixCore/MsixCoreInstaller/ValidateTargetDeviceFamily.hpp
There could be multiple target device families listed in an app manifest. Currently, the code does not check for compatibility of multiple TDF's. ValidateTargetDeviceFamily.cpp should return S_OK if any one of them is compatible with the OS.
If none of them are compatible, ERROR_INSTALL_REJECTED is returned.
> Validate multiple target device families in app manifest

- preview/MsixCore/MsixCoreInstaller/InstallUI.cpp
The text 'Installing app package 100%' would still be displayed on the UI after app installation is complete. This should be hidden after app installation is complete.
> Hide percentage windows after install is complete

- src/inc/DeflateStream.hpp
- src/inc/MsixErrors.hpp
- src/inc/RangeStream.hpp
- src/inc/VectorStream.hpp
- src/inc/ZipFileStream.hpp
- src/msix/CMakeLists.txt
- src/msix/pack/AppxPackageWriter.cpp
- src/msix/pack/DeflateStream.cpp
- src/msix/unpack/ZipObject.cpp
Implement DeflateStream
Uses previous implementations of ZipFileStream and RangeStream.
For pack, RangeStream will create a VectorStream. If the file needs to be compressed, it will create then  DeflateStream passing that VectorStream.
DeflateStream will deflate the buffer until IStream::Write is called with 0 bytes. This is because we need to terminate the stream using Z_FINISH.
> DeflateStream

- preview/MsixCore/MsixCoreInstaller/MsixCoreInstaller.vcxproj
- preview/MsixCore/MsixCoreInstallerLib/MsixCoreInstallerLib.vcxproj
MsixCore currently fails to compile with `Debug/x86` and `Release/x86`.
- MsixCoreLib: Remove the useless (and faulty for x86) post-action
- MsixCore: Use `/MTd` instead of `/MT` when using Debug/x86.
Tested with Debug/x86, Debug/x64, Release/x86 and Release/x64
> Fix x86 compilation of MsixCore

- preview/MsixCore/MsixCoreInstaller/IPackageHandler.hpp
- preview/MsixCore/MsixCoreInstaller/InstallUI.cpp
- preview/MsixCore/MsixCoreInstaller/MsixCoreInstaller.cpp
- preview/MsixCore/MsixCoreInstaller/MsixRequest.cpp
- preview/MsixCore/MsixCoreInstaller/PopulatePackageInfo.hpp
- preview/MsixCore/MsixCoreInstallerLib/PackageManager.cpp
- preview/MsixCore/MsixCoreInstallerLib/PackageManager.hpp
- preview/MsixCore/MsixCoreInstallerLib/inc/IPackageManager.hpp
Add ErrorHandlingMode enum and column to the HandlerInfo registration tables, and modified ProcessAddRequest/ProcessRemoveRequest to handle the behaviors. replacing the IsMandatory() checks.
Fix crash when package open fails by checking for the error.
Return command line string when failure happens in quiet mode.
> Error handling changes

- preview/MsixCore/MsixCoreInstaller/MsixCoreInstaller.vcxproj
- preview/MsixCore/MsixCoreInstallerLib/MsixCoreInstallerLib.vcxproj
Fix some issues with runtime library:
- At the moment, Debug/x64 uses /MDd (Runtime library = Multi-threaded DLL debug) instead of /MTd (Multi-threaded debug) similarly to all other compilation modes.
- MsixInstallerLib used the non-debug version of the runtime library with Debug/x86.
> [MsixCore] Debug/x64 must use /MTd instead /MDd

- preview/MsixCore/MsixCoreInstaller/ErrorHandler.cpp
- preview/MsixCore/MsixCoreInstaller/MsixRequest.cpp
- preview/MsixCore/MsixCoreInstaller/MsixRequest.hpp
- preview/MsixCore/MsixCoreInstaller/PopulatePackageInfo.cpp
- preview/MsixCore/MsixCoreInstaller/PopulatePackageInfo.hpp
- preview/MsixCore/MsixCoreInstaller/ProcessPotentialUpdate.cpp
- preview/MsixCore/MsixCoreInstallerLib/PackageManager.cpp
- preview/MsixCore/MsixCoreInstallerLib/PackageManager.hpp
- preview/MsixCore/MsixCoreInstallerLib/inc/IPackageManager.hpp
Fix #121
> In addition to the 2 existing functions AddPackage(wstring filepath...) and AddPackageAsync(wstring filepath....) using a file path to represent a msix package file, MsixCore should also support the installation of Msix packages not stored as files but as streams.
Modify `AddPackage` and `AddPackageAsync` to replace the file path by a `IStream`:
```cpp
HRESULT AddPackage(IStream * packageStream, DeploymentOptions options);`
```
```cpp
std::shared_ptr<IMsixResponse> AddPackageAsync(IStream * packageStream, DeploymentOptions options, std::function<void(const IMsixResponse&)> callback = nullptr);`
```
And add 2 methods with the same prototype than the 2 original methods to still support installation of packages based on a file path.
MsixRequest was also modified to use a `IStream` …
> [MsixCore] Support installation of packages via IStream

- preview/MsixCore/MsixCoreInstaller/PrepareDevirtualizedRegistry.cpp
Addressing bug in code due to which certain packages were not being installed. 
**Issue:** In cases where the registry file does not exist in case of certain packages, CopyFile was returning an error and the installer crashes. 
**Solution:** Handled this by checking if registry file exists before copying it over and passing it further down.
> Check if registry file exists before copying file over

- src/inc/AppxBlockMapWriter.hpp
- src/inc/AppxPackaging.hpp
- src/inc/MsixErrors.hpp
- src/makemsix/main.cpp
- src/msix/CMakeLists.txt
- src/msix/msix.cpp
- src/msix/pack/AppxBlockMapWriter.cpp
- src/msix/pack/AppxPackageWriter.cpp
- Add MSIX_PACKUNPACK_OPTION flat to PackPackage entrypoint. This allows us to follow the same patter as UnpackPackage and be open future changes are not validation switches instead of creating a new entrypoint. For example, we might allow naming the package after the package id from the manifest. 
- Move SHA256 hashing inside the BlockMapWriter. I realized that there was need to the AppxPackageWriter to the hashing, just pass the block to the block map writer and encapsulate the SHA256 hashing and the base64 encoding.
- Add compiler and linker flags to hide visibility and discard unused functions for Android. This result in a 10KB drop in the binary size.
> Minor pack improvements

- preview/MsixCore/MsixCoreInstaller/MsixCoreInstaller.cpp
- Updated code to redirect to native app installer in case of windows 1709 and above.
> Pass to win10 installer on 1709 or greater

- makewin.cmd
- src/inc/BlockMapStream.hpp
- src/inc/DeflateStream.hpp
- src/inc/Exceptions.hpp
- src/inc/ObjectBase.hpp
- src/inc/RangeStream.hpp
- src/inc/StreamHelper.hpp
- src/inc/VectorStream.hpp
- src/inc/ZipFileStream.hpp
- src/inc/ZipObject.hpp
- src/inc/ZipObjectWriter.hpp
- src/msix/common/ZipObject.cpp
- src/msix/pack/AppxPackageWriter.cpp
- src/msix/pack/ZipObjectWriter.cpp
- src/msix/unpack/ZipObjectReader.cpp
This change generally improves packing, as well as making a slightly more sweeping change to the zip serialization code.  Changes include:
- In debug builds on Windows, don't assert unless the debugger is attached
- Usage changes to FieldBase, and addition of OptionalFieldBase
- Additionally, writing the bytes out no longer requires allocation of hundreds of tiny vectors
- Changing stream usage for writing to be more consistent with usage for reading
- This means instead of ZipFileStream -> RangeStream -> DeflateStream -> VectorStream on RangeStream's vector, we have DeflateStream -> ZipFileStream -> RangeStream -> output stream
- This also means that we avoid holding entire zip'd streams in memory, instead writing directly to output as we go
- Changed Zip64ExtendedInformation to support …
> General improvements to pack

- src/test/msixtest/CMakeLists.txt
- src/test/msixtest/PAL/Pack/NonWindows/PackValidation.cpp
- src/test/msixtest/PAL/Pack/Windows/PackValidation.cpp
- src/test/msixtest/inc/PackValidation.hpp
- src/test/msixtest/inc/msixtest_int.hpp
- src/test/msixtest/pack.cpp
Adds verification of output package via the Windows AppxPackaging APIs in Pack_Good.
CoCreates Windows implementation of AppxFactory and validates the stream by creating the windows implementation of package reader via CreatePackageReader.
> Validate output pack package using the Windows AppxPackaging APIs

- CMakeLists.txt
- makelinux.sh
- makemac.sh
- makewin.cmd
- pipelines/azure-pipelines-linux.yml
- pipelines/azure-pipelines-macos.yml
- pipelines/azure-pipelines-windows.yml
Turn off pack support as the default option for the MSIX SDK.
To enable packing, pass the --pack flag to makewin.cmd, makemas.sh or makelinux.sh or MSIX_PACK=on as a CMake parameter.
> Make MSIX_PACK as non default option

- src/inc/AppxManifestObject.hpp
- src/inc/AppxPackaging.hpp
- src/inc/IXml.hpp
- src/msix/PAL/XML/AOSP/XmlObject.cpp
- src/msix/PAL/XML/Apple/NSXmlParserDelegateWrapper.mm
- src/msix/PAL/XML/Apple/XmlDocumentReader.hpp
- src/msix/PAL/XML/Apple/XmlObject.cpp
- src/msix/PAL/XML/msxml6/XmlObject.cpp
- src/msix/PAL/XML/xerces-c/XmlObject.cpp
- src/msix/PAL/java/com/microsoft/msix/XmlElement.java
- src/msix/common/AppxManifestObject.cpp
- src/msix/common/IXml.cpp
- src/test/mobile/AndroidBVT/app/src/main/cpp/native-lib.cpp
- src/test/mobile/AndroidBVT/build.gradle
- src/test/mobile/AndroidBVT/gradle/wrapper/gradle-wrapper.properties
- src/test/mobile/iOSBVT/iOSBVT.xcodeproj/project.pbxproj
- src/test/msixtest/api_manifestreader.cpp
- src/test/msixtest/inc/msixtest_int.hpp
- src/test/msixtest/msixtest.cpp
- src/test/testData/manifest/Sample_AppxManifest.xml
We failed obtaining all the elements under different namespaces for Xerces, MacOS and iOS.
For example, from the xml below, we didn't get the elements that are under uap and rescap namespace.
```
<Capabilities>
<Capability Name="internetClient"/>
<Capability Name="privateNetworkClientServer"/>
<uap:Capability Name="videosLibrary"/>
<uap:Capability Name="removableStorage"/>
<rescap:Capability Name="enterpriseDataPolicy"/>
<rescap:Capability Name="previewStore"/>
</Capabilities>
```
For Xerces, stop using Xerces's xpath as it doesn't support getting all namespaces and walk through the elements via getElementsByTagNameNS using namespaceURI "*" that matches all namespaces. We need to turn-on setDoNamespaces, even for non-validation parser.
For Apple parser, didStartElement always had …
> Fix not getting elements that belongs to different namespaces

- CMakeLists.txt
- cmake/msix_resources.cmake
- sample/BundleSample/CMakeLists.txt
- sample/CMakeLists.txt
- sample/ExtractContentsSample/CMakeLists.txt
- sample/OverrideLanguageSample/CMakeLists.txt
- sample/OverrideStreamSample/CMakeLists.txt
- sample/PackSample/CMakeLists.txt
- src/CMakeLists.txt
- src/makemsix/CMakeLists.txt
- src/msix/CMakeLists.txt
- src/test/CMakeLists.txt
- src/test/msixtest/CMakeLists.txt
Using CMAKE_BINARY_DIR makes the copies the msix.dll binary, for the test and samples output directory, in the wrong location when this project is added as a submodule/subtree
This fix sets MSIX_PROJECT_ROOT and MSIX_BINARY_ROOT to the correct project and binary directories in the top level CMakeLists.txt and use them instead of CMAKE_PROJECT_ROOT and CMAKE_BINARY_DIR  respectively across the entire project.
Also, moved copying msix.dll to <build dir>/samples and <build dir>/msixtest from src/msix/CMakeLists.txt to the CMakeLists.txt for tests and samples.
> Isolate MSIX SDK build directory from other projects.

- preview/MsixCore/msixmgr/InstallUI.cpp
When launch checkbox is unchecked after clicking on install button, the app should launch and the installer window should close.
> Bug: Close installer window after launching app when launch checkbox is unchecked

- CMakeLists.txt
- cmake/msix_resources.cmake
- sample/BundleSample/CMakeLists.txt
- sample/ExtractContentsSample/CMakeLists.txt
- sample/OverrideLanguageSample/CMakeLists.txt
- sample/OverrideStreamSample/CMakeLists.txt
- sample/PackSample/CMakeLists.txt
- src/makemsix/CMakeLists.txt
- src/msix/CMakeLists.txt
- src/test/msixtest/CMakeLists.txt
makemsix, msixtest and samples include the headers the sdk publishs via ${CMAKE_BINARY_DIR}/src/msix. When this project is added as a submodule, CMAKE_BINARY_DIR points to the root binary location which is not were the headers are published. This changes uses MSIX_BINARY_ROOT instead of CMAKE_BINARY_DIR to resolve this. 
Also, remove extra include that isn't needed and output the resource zip to MSIX_BINARY_ROOT
> Use MSIX_BINARY_ROOT instead of CMAKE_BINARY_DIR

- CMakeLists.txt
- src/msix/AppxFactory.cpp
Added implementation for the CreateBundleManifestReader API.
These changes will enable the application of ACLs to package folders, which is new functionality we are adding to msixmgr.exe.
> Implement CreateBundleManifestReader

- README.md
- pipelines/azure-pipelines-windows.yml
Update readme adding packaging information. I recommend looking [here](https://github.com/microsoft/msix-packaging/blob/packaging-readme/README.md) to read the readme as it will look on GitHub
- Update build tags with all the platforms and variations that we support. Some of them will appear as unknown, this is because they are querying the latest build in master and it doesn't exists yet.
- Update information about testing.
- Fix some misinformation for Win7 support
- Remove old '--no-pack ' option for some builds.
> Packaging readme

- cmake/msix_resources.cmake
- src/msix/common/AppxFactory.cpp
Starting in cmake 3.15, the tar command will error if given no files to work on.  This change will work across all version by cutting off that scenario and instead generating a 1 byte resource array.  The code is then updated to recognize that scenario and short circuit to returning a file not found for any resources requested.
> Fix for new cmake tar command that won't take no files

- src/inc/public/AppxPackaging.hpp
- src/msix/PAL/XML/AOSP/XmlObject.cpp
- src/msix/PAL/XML/Apple/XmlObject.cpp
- src/msix/PAL/XML/msxml6/XmlObject.cpp
- src/msix/PAL/XML/xerces-c/XmlObject.cpp
Rename the XML interface variable to indicate that it is an xpath query and not just an element name.
> Rename variable to indicate semantics

- preview/MsixCore/msixmgr/Constants.hpp
- preview/MsixCore/msixmgr/ValidateTargetDeviceFamily.cpp
Updated ValidateTargetDeviceFamily.cpp to perform CaseInsensitive comparison when matching Target device family from manifest to either of MSIXCore.Desktop or MSIXCore.Server
> Case insensitive TDF comparison

- preview/MsixCore/README.md
- preview/MsixCore/Tests/test.ps1
- preview/MsixCore/msixmgr/msixmgr.cpp
- preview/MsixCore/msixmgrLib/PackageManager.cpp
Modified code to enable search by package family name. Also , enabled searching by wildcards(*(match any character) and ?(match single character)). 
When packageFullName or packageFamilyName is passed using wildcards, such as,
msixmgr.exe -FindPackage ***photos***, 
msixmgr.exe -FindPackage *adplus_8wekyb3d8bbw? (PackageFamilyName using wildcards)
it should return the appropriate results.
> Find package by family name and wildcard support

- preview/MsixCore/msixmgr/UnpackProvider.cpp
- preview/MsixCore/msixmgr/UnpackProvider.hpp
- preview/MsixCore/msixmgr/msixmgr.cpp
Added warning informing the user that if the package is a store-signed package, they'll need to include a license file.
Added warning informing the user what framework packages the package depends on. 
Added suggestion to unpack to a larger VHD when a FileWrite error occurs.
> Added warnings for required dependency packages/required license files

- preview/MsixCore/msixmgr/InstallUI.cpp
UI used to display detailed percentage while installing an app. Converted this to int, so display is in the format, 50% without decimals.
> Convert display percent from float to int

- src/inc/internal/FileStream.hpp
- src/msix/common/Encoding.cpp
- src/msix/unpack/AppxPackageObject.cpp
- Adds support for unpacking extremely large files on Windows. Previously, this would fail in FileStream.hpp's Seek() because the function would call std::fseek and try to pass in a very large value for the offset parameter. This value is first cast to a long, but on Windows a long is 32 bits, but the original value is 64 bits. As a result, the offset value becomes negative after being cast to a long, and the call to std::fseek fails because you can’t specify a negative offset. The fix was to call _fseeki64 instead of std::fseek and _ftelli64 instead of std::ftell.
- Fixes the EncodingToChar array in Encoding.cpp. Previously, some of the values did not match up with what's defined in the std::array PercentageEncoding
- Ensures that filenames are always decoded during unpacking, not just …
> Fix decoding problems and add support for unpacking large files on Windows

- preview/MsixCore/msixmgr/Constants.hpp
- preview/MsixCore/msixmgr/MsixRequest.hpp
- preview/MsixCore/msixmgr/ProcessPotentialUpdate.cpp
- preview/MsixCore/msixmgr/RegistryDevirtualizer.cpp
- preview/MsixCore/msixmgr/RegistryKey.cpp
- preview/MsixCore/msixmgr/RegistryKey.hpp
- preview/MsixCore/msixmgr/VirtualFileHandler.cpp
- preview/MsixCore/msixmgr/VirtualFileHandler.hpp
- preview/MsixCore/msixmgrLib/GeneralUtil.cpp
- preview/MsixCore/msixmgrLib/GeneralUtil.hpp
Add refcount to SharedDLLs key if we're devirtualizing a file to a path that already exists.
When removing a devirtualized file, first check SharedDLLs key and decrement; only delete if decremented to 0.
Also fixing substring matching problem when determining devirtualized folder.
Before: SystemX86 would match into System folder due to System being a substring of SystemX86; resulting in files being sprayed into c:\windows\system32 on 64-bit machine for SystemX86.
After: SystemX86 only matches with SystemX86 as we only match on whole token now.
Registry devirtualization also has same substring matching problem; we will display warnings when there's an incomplete match instead of just blissfully erroneous-matching and not logging anything.
> Shared dll handling

- src/inc/public/MsixErrors.hpp
- src/msix/pack/AppxPackageWriter.cpp
- src/msix/pack/ZipObjectWriter.cpp
- src/test/msixtest/api_packagewriter.cpp
We used to allow adding a file with the same name to the package. The resulting package would seem valid, but it is actually invalid and unpacking will fail, as the blockmap contains multiple entries with the same name. 
This fixes this scenario to fail at packaging time.
> Fix adding multiple files with the same name via AppxPackaging apis

- preview/MsixCore/msixmgr/FilePaths.cpp
- preview/MsixCore/msixmgrLib/GeneralUtil.cpp
Add some VFS file paths that weren't handled previously, and fix caseInsensitiveSubString which would basically always inadvertently return true.
> add VFS file paths and fix caseinsensitiveissubstring

- preview/MsixCore/msixmgr/InstallUI.cpp
- preview/MsixCore/msixmgr/Package.hpp
- preview/MsixCore/msixmgrLib/inc/IPackage.hpp
The package was loading the exe from the VFS location. It should ideally launch from the actual file location. Updated to reflect this.
> Load package from programFiles location

- preview/MsixCore/msixmgr/Extractor.cpp
Apps were failing to install because the filename being passed to the CreateStreamOnFileUTF16 function were longer than 256 characters. Resolved this by appending the passed filename with \\?\.
Tested by installing an app which was failing previously and verified that it now launches.
> Append filepath with long length support

- preview/MsixCore/msixmgr/FilePaths.cpp
Replacing substring check from map with whole string check. Some apps were looking at the wrong path for a file due to this issue after install.
> Replace substring check with full string check

- preview/MsixCore/MsixMgrWix/Product.wxs
More fixup for the broken build -- my local clone did not clean before changing the x64 path, (clean after does not remove the changed location binaries) and so the files still existed in the original location, and so locally it built just fine, but fails on the CI build machine
> update path to custom action for x64 change

- preview/MsixCore/MsixMgrWix/Product.wxs
The product name msixmgr shows up in the UI for MSI dialogs. MSIX Core is preferred as the name that shows up.
> Change msixmgr name to MSIX Core per feedback

- preview/MsixCore/Tests/test.ps1
- preview/MsixCore/msixmgr/Package.cpp
- preview/MsixCore/msixmgr/Package.hpp
Grab package level variables from Properties element instead of the application element: Logo, PublisherDisplay and DisplayName are all available as properties of the package. This provides parity with what desktopappinstaller is doing on win10
#231
> Displayname for package instead of app

- preview/MsixCore/ClickOnceWrapper/msixmgrClickOnceWrapper.csproj
- preview/MsixCore/GetMsixmgrProductsCA/GetMsixmgrProducts.csproj
- preview/MsixCore/MsixMgrWix/MsixMgrWix.wixproj
- preview/MsixCore/msixmgr/msixmgr.vcxproj
- preview/MsixCore/msixmgrLib/msixmgrLib.vcxproj
Fixing recent updates (json and localization) that did not build x86 to reference the correct directories, and also putting the x86 in its own directory similar to x64.
Referencing $platform doesn't work because vs treats the x86 platform as "Win32". So these are hardcoded to x86.
> fix paths for x86 build.

- preview/MsixCore/MsixMgrWix/Product.wxs
- preview/MsixCore/msixmgr/MsixRequest.cpp
- preview/MsixCore/msixmgr/Package.cpp
- preview/MsixCore/msixmgr/Package.hpp
- preview/MsixCore/msixmgr/ValidateArchitecture.cpp
- preview/MsixCore/msixmgr/ValidateArchitecture.hpp
- preview/MsixCore/msixmgrLib/inc/IPackage.hpp
- preview/MsixCore/msixmgrLib/msixmgrLib.vcxproj
Add a ValidateArchitecture handler to block wrong processor architecture installs (i.e. x64 on x86)
Increase size of removal warning in MSI package so it's not cut off.
> Block wrong architecture installs, increase space for removal warning

- preview/MsixCore/msixmgr/PSFScriptExecuter.cpp
- preview/MsixCore/msixmgr/RegistryDevirtualizer.cpp
Registry devirtualizer detokenize (handle the [{System}] etc tokens) was only happening in value data, but we would write the tokens in keynames and value names 
This change detokenizes keynames and value names before writing the data.
Also, need to null out the data buffers when they are re-used, as enumvalue may leave them unmodified when the data is null; this leads to writing whatever the previous value was multiple times instead of writing null.
Fix PSFScriptExecuter from logging nonsense when there's no psf by bailing early when we see there's no PSF.
> Registry devirtualizer fixes

- preview/MsixCore/msixmgr/ProcessPotentialUpdate.cpp
- preview/MsixCore/msixmgrLib/GeneralUtil.cpp
- preview/MsixCore/msixmgrLib/GeneralUtil.hpp
Check version numbers before allowing "updates" to proceed -- only higher versions are allowed. Same version is either a re-install or blocked, same as win10.
> block downgrade from lib

- preview/MsixCore/msixmgr/InstallUI.cpp
- preview/MsixCore/msixmgr/InstallUI.hpp
- preview/MsixCore/msixmgr/WindowsCompatibility.manifest
- preview/MsixCore/msixmgr/msixmgr.rc
- preview/MsixCore/msixmgr/msixmgr.vcxproj
- preview/MsixCore/msixmgr/resource.h
Before: displayed a cmd prompt for the duration of opening a package
After: displays empty UI with Loading package... text.
Noticeable when double clicking large packages.
Before: showed the same capability Uses all system resources text for each capability in the package.
After: shows it once
Before: progress bars/buttons used ancient window style
After: progress bars/buttons use common controls 6, which is slightly less ancient.
> Various UX fixes 

- preview/MsixCore/msixmgr/PSFScriptExecuter.cpp
- preview/MsixCore/msixmgr/Package.cpp
Shore up the error handling of PSF scripts: i.e. handle cases where config.json is missing expected elements and error out instead of just crashing. 
Also, add execution bypass to the command line, so that user do not have to have set script execution to unrestricted in order to run the PSF scripts.
> execution bypass and better psf error checking

- preview/MsixCore/msixmgr/InstallUI.cpp
- preview/MsixCore/msixmgr/InstallUI.hpp
+Resize the logo so that logos larger than the size allotted are shrunk down to fit.
+Combine the two % text controls into one, so that they do not overlap, and so the spacing is not weird in other languages. y is also adjusted slightly so text does not overlap with progress bar, which was causing some flickering.
> Resize ux elements

- MsixCore/msixmgr/FileTypeAssociation.cpp
- MsixCore/msixmgr/RegistryDevirtualizer.cpp
- MsixCore/msixmgr/WriteDevirtualizedRegistry.cpp
Registry.dat provided can be in unexpected formats: we won't fail when it's in an unexpected format; also, if registrydevirtualizer fails during create, we will crash because we did not set it in msixrequest. Consumers of this should check for null before using.
> Dont fail on missing registry

- MsixCore/msixmgr/InstallUI.cpp
Instead of static control, update to readonly richedit control. This enables copy paste as well.
The scroll bar shows up only if the textsize increases the size of the textbox.
> Add Richedit box

- README.md
If you turn on the pack option, the build script requires also the option -DUSE_VALIDATION_PARSE set to on, otherwise the build will fail.
> Added missing parameter to compile makemsix with pack option enabled

- MsixCore/msixmgrLib/GeneralUtil.cpp
**Problem:**
When running the command: 
msixmgr.exe -unpack -packagePath <appx.appxbundle> -destination 
...package paths that did not have a file extension in all lower-case letters (.appxbundle vs. .AppxBundle) would get rejected as invalid package paths. 
**Changes:**
Updated the EndsWith API in GeneralUtils.cpp to make case-insensitive comparisons.
**Validation:**
Successfully unpacked packages and bundles regardless of whether file extension was all lower-case letters.
> Updated EndsWith API in GeneralUtils.cpp to make case-insensitive comparison

- README.md
- cmake/macos.cmake
- makemac.sh
This changes enables building the MSIX SDK to run on Apple Silicon Macs.
Prerequisites:
- Xcode 12 beta Build 12A8161k
Notes: Currently there are two Xcode 12 beta builds: 12A6163b and 12A8161k. 12A6163b does NOT include support for building macOS Universal apps. Also, this is the version that ADO's macOS agents have preinstalled it is not added to our automated builds. When ADO updates their images or when Xcode 12 releases a new change include the build.
> Enable build for Apple Silicon Macs

- sample/BundleSample/BundleSample.cpp
- sample/ExtractContentsSample/ExtractContentsSample.cpp
- sample/OverrideLanguageSample/OverrideLanguageSample.cpp
- sample/OverrideStreamSample/OverrideStreamSample.cpp
- sample/PackSample/PackSample.cpp
- src/inc/public/AppxPackaging.hpp
- src/makemsix/main.cpp
- src/msix/CMakeLists.txt
- src/msix/msix.cpp
Caller can now use MsixGetLogTextUTF8. To avoid compat issues, if GetLogTextUTF8 is not defined we define it.
Address #210.
> Rename GetLogTextUTF8 to MsixGetLogTextUTF8

- src/msix/pack/ContentTypeWriter.cpp
At package time, adding files to the [Content Types].xml where a parent directory contains a "." and the actual file doesn't have an extension incorrectly took that "." from a parent directory as a file extension. For example for ".git/description" produces an Extension element `<Default ContentType="application/octet-stream" Extension="git/description"/>` instead of the correctly Override element `<Override ContentType="application/octet-stream" PartName="/.git/config"/>`
#355 uncovered this issue but incorrectly states that the .git folder was not in the package.
> Fix [Content Types].xml creation for files without an extension

- src/inc/internal/DirectoryObject.hpp
- src/msix/PAL/FileSystem/POSIX/DirectoryObject.cpp
- src/msix/PAL/FileSystem/Win32/DirectoryObject.cpp
- src/test/msixtest/pack.cpp
Fixes #354 
Pack always appends the specific path separator to the input directory. Because not having a path separator is required in other places in the code, it was easier to just remove it in the constructor if its present.
> Fix - Makemsix pack fails when directory given ends with "\"

- tools/utils/SignConfig.xml
- tools/utils/Utils/Properties/AssemblyInfo.cs
- tools/utils/Utils/Utils.nuspec
- tools/utils/custom.props
All of this is to be consumed by the release pipeline.
* Added configuration for signing.
* Added build properties to control major/minor version with recommended semantic versioning. Patch version is set by the pipeline.
* Added .nuspec file to indicate license and package name. Remaining fields are taken from the .csproj/AssemblyInfo.
* Updated AssemblyInfo with required information.
> Add configuration files to create Utils NuGet package

- tools/utils/Utils/Utils.nuspec
Adding properties required to the .nuspec that I missed before. Also replaced some tokens by the actual values as our build system rewrites the AssemblyInfo where they were taken from.
> Add missing required properties for Utils NuGet

- README.md
- cmake/macos.cmake
- pipelines/azure-pipelines-macos.yml
Azure DevOps's Mac Microsoft-hosted agents now include a version of Xcode that can build targeting macOS. Adding it to pipelines.
> Adding macOS Sillicon to pipelines

- README.md
- pipelines/azure-pipelines-ios.yml
- pipelines/azure-pipelines-macos.yml
- pipelines/azure-pipelines-windows.yml
- pipelines/templates/macos-universal.yml
macOS universal binaries are executables that run natively on both Apple silicon and Intel-based Mac computers. These are created by providing the architecture specific binaries to the `lipo` tool for it to merge. The new jobs will wait for the binaries to be built and combine them.
Also, adding new build badges to the README.md, update the link for the az devops images used and fix some typos in the artifacts names.
> macOS universal binaries

- pipelines/azure-pipelines-linux.yml
Missing package.nuspec and files under the build directory.
> Add missing files to Linux artifacts

- tools/pipelines-tasks/azure-pipelines/localization.yml
The loc pipeline for the ADO tasks was missing a parameter for where to place the localized strings. By default it is the repo root which made sense in the internal repo but not here.
> Fix output path in localization pipeline for ADO tasks

- tools/utils/Utils/AppxPackaging/AppxMetadata.cs
I'd like to be able to create an AppxMetadata object for a package within an AppxBundle, but currently there's no way to do that. This will allow the following code:
```
var bundle = new Microsoft.Msix.Utils.AppxPackaging.AppxBundleMetadata(file);
IAppxFile appxFile = bundle.AppxBundleReader.GetPayloadPackages().GetCurrent();
var stream = appxFile.GetStream();
var metadata = new AppxMetadata(stream);
```
> Adding AppxMetadata constructor that takes an IStream

- tools/pipelines-tasks/.gitignore
- tools/pipelines-tasks/.vscode/launch.json
- tools/pipelines-tasks/MsixAppAttach/index.ts
- tools/pipelines-tasks/MsixPackaging/msbuild.ts
- tools/pipelines-tasks/SignConfig.xml
- tools/utils/SignConfig.xml
The pipeline tasks for packaging and for creating a VHDX for app attach call a helper PS script, which may be blocked in certain environments due to the ExecutionPolicy. To allow the scripts to run, set the execution policy when calling powershell.exe.
Also removed files regarding release signing configuration that are no longer needed with the new signing method, and added debug configuration for the pipelines tasks that was missing after the move from the private repo.
> Set ExecutionPolicy when calling powershell in pipeline tasks

- tools/pipelines-tasks/AppInstallerFile/appinstallerfile.ts
- tools/pipelines-tasks/test/appinstallerfile.ts
- tools/pipelines-tasks/test/assets/expected/appinstallerfile-new-from-package-success.appinstaller
- tools/pipelines-tasks/test/assets/expected/appinstallerfile-update-from-package-success.appinstaller
- tools/pipelines-tasks/test/mock-tests/appinstallerfile-new-from-package-success.ts
When generating an App Installer file with the DevOps task, the settings for update on launch should be attributes but they were being generated as elements in the XML. Change to using attributes, update test to check for this and fix error in tests to actually validate the generated file.
This fixes #405
> Use attributes instead of elements on generated .appinstaller files

- tools/pipelines-tasks/AppInstallerFile/Strings/resources.resjson/en-US/resources.resjson
- tools/pipelines-tasks/AppInstallerFile/index.ts
- tools/pipelines-tasks/AppInstallerFile/task.json
- tools/pipelines-tasks/AppInstallerFile/task.loc.json
- tools/pipelines-tasks/MsixPackaging/Strings/resources.resjson/en-US/resources.resjson
- tools/pipelines-tasks/MsixPackaging/task.json
- tools/pipelines-tasks/MsixPackaging/task.loc.json
- tools/pipelines-tasks/azure-pipelines/ci-build.yml
- tools/pipelines-tasks/build.ps1
- tools/utils/azure-pipelines.yml
Issue: The packaging extension fails to install on Azure DevOps Server due to how we used input groups in the tasks. The visibility of some inputs in one group depended on inputs from another group, but that is not allowed there.
Fix: Removed the input groups altogether. The UI is a little more cluttered, but this allows to install.
Validated install works in a local server.
Also updated the build script to prevent updating packages depended on while building.
See #400
> Remove task input groups

- src/msix/PAL/Signature/Win32/SignatureValidator.cpp
- src/msix/common/UnicodeConversion.cpp
**Issue:** The installation was failing if the app had an accent in the subject name of the certificate or the publisher in the manifest.
**Reason**: 
The equals comparison check between the publisher name derived from the certificate and the publisher name from the appx manifest file was failing. It appears that the value of the 'publisher' being read from the signature file(certificate) was being read and derived using CertNameToStrA which was returning the ANSI string. I changed it to CertNameToStrW which now returns the correct UTF8 string.
**Verified**: by running an app which is signed with a certificate which has the following special characters content in it subject name and manifest publisher name - Île-de-France. It installs and runs successfully.
> Installation fails if certificate contains extended ascii or non alpha-numeric character

- src/msix/PAL/Signature/OpenSSL/SignatureValidator.cpp
* OpenSSL is not thread-safe even when compiled with OPENSSL_THREADS
* Library initialization needs to be called only once and
* Needs to set a thread ID callback
* Needs to set locking callback
* OPENSSL_add_all_algorithms() should be called only once in an app
* Addresses [Bug 411](https://github.com/microsoft/msix-packaging/issues/411)
> OpenSSL Thread Safety

- src/msix/PAL/Signature/OpenSSL/SignatureValidator.cpp
* OpenSSL is not thread-safe even when compiled with OPENSSL_THREADS
* Library initialization needs to be called only once and
* Needs to set a thread ID callback
* Needs to set locking callback
* OPENSSL_add_all_algorithms() should be called only once in an app
Co-authored-by: Sayan Chaliha <sachalih@microsoft.com>
> Cherry-pick: OpenSSL Thread Safety (#412)

- tools/pipelines-tasks/AppInstallerFile/package-lock.json
- tools/pipelines-tasks/MsixAppAttach/index.ts
- tools/pipelines-tasks/MsixAppAttach/package-lock.json
- tools/pipelines-tasks/MsixPackaging/msbuild.ts
- tools/pipelines-tasks/MsixPackaging/package-lock.json
- tools/pipelines-tasks/MsixSigning/package-lock.json
- tools/pipelines-tasks/common/helpers.ts
Some tasks in the packaging extension call PowerShell scripts using unquoted strings, which fails in environments where the paths include spaces. This change adds quotes to the string paths to fix that.
This should fix #410
> Quote script paths in extension tasks

- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
This is the pipeline for building the VSIX for release of the extension. It used to be a classic pipeline; moving it to yaml for better change tracking. This builds and signs the packages, then publishes a private version of it for validation. The actual publishing will be a separate release pipeline.
> Add yaml pipeline for building the VSIX for MSIX Packaging Extension

- tools/utils/Utils/Telemetry/TelemetryEventSource.cs
- tools/utils/Utils/Utils.csproj
The TelemetryEventSource from the Msix-packaging library causes a namespace conflict with other projects that want to implement their own managed-code telemetry. By removing this flag and making this class internal, it allows us to create our own telemetry implementation without a namespace conflict.
> Remove TELEMETRYEVENTSOURCE_PUBLIC flag to resolve namespace conflict with external TelemetryEventSource.cs

- src/inc/internal/AppxBlockMapWriter.hpp
- src/inc/internal/AppxFactory.hpp
- src/inc/internal/AppxPackageWriter.hpp
- src/inc/public/AppxPackaging.hpp
- src/msix/CMakeLists.txt
- src/msix/common/AppxFactory.cpp
- src/msix/msix.cpp
- src/msix/pack/AppxBlockMapWriter.cpp
- src/msix/pack/AppxPackageWriter.cpp
- src/test/msixtest/api_packagewriter.cpp
- src/test/msixtest/testData/PackTestData.cpp
Since the open source MSIX SDK used to validate schema of the block map xml, the last change to add <FileHash> to the block map xml will break older version of the MSIX SDK if the users haven't updated to the latest version. In order not to break those older MSIX SDKs and give users options to transition to the latest SDK, this change will add an option to IAppxFactory creation to enable file hash for the package writer and by default NOT creating <FileHash> to be aligned with old behavior. To enable file hash in block map, the code should call a new method CoCreateAppxFactoryWithHeapAndOptions, which passes in a new MSIX_FACTORY_OPTIONS flag MSIX_FACTORY_OPTION_WRITER_ENABLE_FILE_HASH to create an IAppxFactory object. From it, the created package writer will use the new block map xml …
> Added option to AppxFactory to create package writer with file hash enabled

- tools/pipelines-tasks/.mocharc.yml
- tools/pipelines-tasks/AppInstallerFile/package-lock.json
- tools/pipelines-tasks/AppInstallerFile/package.json
- tools/pipelines-tasks/MsixAppAttach/package-lock.json
- tools/pipelines-tasks/MsixAppAttach/package.json
- tools/pipelines-tasks/MsixPackaging/MSBuildHelpers/package-lock.json
- tools/pipelines-tasks/MsixPackaging/MSBuildHelpers/package.json
- tools/pipelines-tasks/MsixPackaging/package-lock.json
- tools/pipelines-tasks/MsixPackaging/package.json
- tools/pipelines-tasks/MsixSigning/package-lock.json
- tools/pipelines-tasks/MsixSigning/package.json
- tools/pipelines-tasks/common/package-lock.json
- tools/pipelines-tasks/common/package.json
- tools/pipelines-tasks/package-lock.json
- tools/pipelines-tasks/package.json
Bumping the minor versions of all dependencies for the MSIX Packaging Extension to the latest available.
Main reason is to fix a case of [CVE-2021-23358](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23358) through a dependency of azure-devops-node-api
> Bump DevOps Extension dependencies' version

- tools/utils/Utils/AppxPackaging/AppxBundleMetadata.cs
- tools/utils/Utils/AppxPackaging/AppxMetadata.cs
- tools/utils/Utils/AppxPackaging/ChildPackageMetadata.cs
Adds new property on `AppxBundleMetadata: ChildAppxPackages`. This replaces the now `[Obsolete]` InternalAppxPackagesRelativePaths, as it has the file paths but also the metadata unique to each child package.
> Adding property on bundle object containing metadata about child packages

- src/msix/PAL/Signature/OpenSSL/SignatureValidator.cpp
Problem:
* SignatureValidator::IsStoreOrigin() tries to read X.509 extensions
to determine if the origin of the signature matches the Windows Store OID.
* Extension data is converted from a raw buffer to an std::string for
comparision.
* The raw buffer is not null-terminated, and therefore, running
std::strlen() on it causes invalid memory access.
* This invalid access is caught by ASAN on macOS.
Solution:
* Null-terminate the raw buffer before trying to build an std::string
from it.
Tests:
* Ran app test suite that uses libmsix.dylib with ASAN on. No crashes
were reported.
> Invalid Memory Access in SignatureValidator

- src/msix/PAL/Signature/OpenSSL/SignatureValidator.cpp
* Invalid Memory Access in SignatureValidator
Problem:
* SignatureValidator::IsStoreOrigin() tries to read X.509 extensions
to determine if the origin of the signature matches the Windows Store OID.
* Extension data is converted from a raw buffer to an std::string for
comparision.
* The raw buffer is not null-terminated, and therefore, running
std::strlen() on it causes invalid memory access.
* This invalid access is caught by ASAN on macOS.
Solution:
* Null-terminate the raw buffer before trying to build an std::string
from it.
Tests:
* Ran app test suite that uses libmsix.dylib with ASAN on. No crashes
were reported.
* Invalid Memory Access in SignatureValidator
Problem:
* As @JohnMcPMS pointed out, writing "" with 1 byte size is null termination.
* A better solution would be to use …
> Invalid Memory Access in SignatureValidator (#453)

- pipelines/azure-pipelines-macos.yml
This changes address #392 and reenable the arm64 builds for macOS.
> Enable arm64 builds in macOS

- MsixCore/msixmgr/msixmgr.cpp
**Problem**
During the CIM creation process, the given package or directory first gets unpacked to a temporary directory under the working directory. Some files within these packages end up having absolute file paths whose lengths exceed the maximum path length. This causes problems down the road for components that call APIs that take these paths as a parameter but are unable to handle them.
**Fix:**
When creating the temporary directory, use a path name with the long path prefix appended.
**Validated**
- Confirmed that the CIM creation failure no longer repros after the change is applied.
- Executed automated tests to confirm no regressions were caused.
- Stefan independently validated the fix as well.
> Handle long file paths during CIM creation

- tools/utils/Utils/AppxPackaging/AppxBundleMetadata.cs
- tools/utils/UtilsTests/ProcessRunnerTests/ProcessRunnerTests.cs
When reading the metadata from a bundle we would also read its references to optional packages. The API for this was added in version 1703, so creating the metadata object would fail older OS versions.
Changed to populate this information only when it is requested. Accessing to these properties on older OS versions would still fail, but construction and the remaining properties work.
> Msix.Utils - Make reading of bundle optional packages happen only when needed

- src/makemsix/main.cpp
This PR includes various minor clenaups to the makemsix help messages, the most impactful change is probably the
removal of part of the `bundle` command description that referred to options that do not even exist (anymore?).
> Various makemsix help message improvements

- src/inc/shared/TimeHelpers.hpp
- src/msix/CMakeLists.txt
- src/msix/common/TimeHelpers.cpp
- src/msix/common/ZipObject.cpp
- src/test/msixtest/CMakeLists.txt
- src/test/msixtest/TimeHelpers_ut.cpp
Fix #393 
For convenience, we use some magic number in the last modify date and time in the LFH and CDH. This produce the behavior described by #393.
This change gets the local system time and convert it to MS-DOS date and time format and add it to the headers. It also follows the makeappx implementation that if getting the time fails the default is 12/31/2107, 23:59:58.
Validated in Windows and macOS.
> Use MS-DOS time in LFH and CDH

- pipelines/azure-pipelines-aosp.yml
- pipelines/azure-pipelines-ios.yml
- pipelines/azure-pipelines-linux.yml
- pipelines/azure-pipelines-macos.yml
- pipelines/azure-pipelines-windows.yml
- pipelines/templates/build-windows.yml
- tools/pipelines-tasks/azure-pipelines/ci-build.yml
- tools/utils/azure-pipelines.yml
Adding weekly builds so that we can run static code analysis and get new detections even if there are no code changes.
> Add scheduled weekly builds for MSIX SDK, MSIX.Utils, and the AzDO tasks extension

- src/msix/common/ZipObject.cpp
* CentralDirectoryFileHeader and LocalFileHeader uses MsDosDateAndTime.
* MsDosDateAndTime is allocated (`new`) and not deallocated (`delete`).
* MsDosDateAndTime doesn't need to be allocated in the heap.
> Fix memory leaks ZipObject.cpp

- tools/utils/UtilsTests/UtilsTests.csproj
Per https://github.com/advisories/GHSA-5crp-9r3c-p9vr, we should update the dependency we had on Newtonsoft to at least v13.0.1. We had it as a transitive dependency from Microsoft.NET.Test.Sdk; so we had to update that. The new version of Newtonsoft is used starting on the latest v17.4 of Microsoft.NET.Test.Sdk.
This was only present in the test code, so we won't need to make a new release of the Utils.
> Update Microsoft.NET.Test.Sdk NuGet dependency on MSIX.Utils tests

- tools/pipelines-tasks/AppInstallerFile/package.json
- tools/pipelines-tasks/MsixAppAttach/package.json
- tools/pipelines-tasks/MsixPackaging/package.json
- tools/pipelines-tasks/MsixSigning/package.json
- tools/pipelines-tasks/common/package.json
This fixes some typos in the author listed in the `package.json` for the Node modules that make up the AzDO tasks. The actual author used for the task is defined in the `task.json`, where it is spelled correctly.
Fixes #521
> Fix typo in author name in `package.json`

- tools/pipelines-tasks/AppInstallerFile/package-lock.json
- tools/pipelines-tasks/AppInstallerFile/package.json
- tools/pipelines-tasks/MsixAppAttach/package-lock.json
- tools/pipelines-tasks/MsixAppAttach/package.json
- tools/pipelines-tasks/MsixPackaging/MSBuildHelpers/package.json
- tools/pipelines-tasks/MsixPackaging/package-lock.json
- tools/pipelines-tasks/MsixPackaging/package.json
- tools/pipelines-tasks/MsixSigning/package-lock.json
- tools/pipelines-tasks/MsixSigning/package.json
- tools/pipelines-tasks/common/package-lock.json
- tools/pipelines-tasks/common/package.json
- tools/pipelines-tasks/package-lock.json
- tools/pipelines-tasks/package.json
Update dependencies for the pipeline tasks all at once, instead of one file at a time like dependabot did.
Note: The tests failed in dependabot's PRs, so I'm waiting to see if they fail here; hopefully we just needed to update all at once. Locally I didn't get the same errors as in the pipeline, though I haven't gotten a clean run because I missed some setup step.
Closes #536
Closes #537
Closes #538
Closes #539 
Closes #540 
Closes #541
> Update dependencies for pipeline tasks

- tools/utils/README.md
- tools/utils/UtilsTestExe/UtilsTestExe.csproj
- tools/utils/UtilsTests/UtilsTests.csproj
- tools/utils/azure-pipelines.yml
The pipeline for the Utils package started failing when running the tests with error
```
##[error]Testhost process for source(s) 'D:\a\1\s\tools\utils\UtilsTests\bin\Release\net5.0\UtilsTests.dll' exited with error: You must install or update .NET to run this application.
```
The ultimate reason seems to be that since .NET 5 is no longer supported, the pipelines don't like it anymore. The solution was to update the test project to .NET 6; luckily no changes were required.
Replaces #550. This time I could actually confirm that the pipeline works correctly by making the branch in the official repo...
> Update Utils test project to .NET6

- src/inc/internal/IXml.hpp
- src/inc/public/MSIXWindows.hpp
- src/msix/PAL/Signature/OpenSSL/SignatureValidator.cpp
Two commits here:
1. Fix build issues under GCC:
a. _SIZE_T_DEFINED under GCC means that `size_t` is defined, but not `SIZE_T`. We should use something more windows-specific here. It's safe, since non-windows toolchains don't define `SIZE_T` by themselves.
b. Missing return from a function triggers a warning, even though this function never gets truly compiled. Probably an old GCC bug.
2. Add support for non-store Microsoft signatures for OpenSSL-based signature validator.
a. Export a FULL TRUSTED cert chain from validation process. This chain shall contain both the root certificate (last in chain) AND the signing certificate (first in chain).
b. Consider package origin as SignatureOrigin::Windows if and only if:
- Chain is fully trusted.
- Root certificate comes from Microsoft Root …
> SignatureOrigin::Windows for OpenSSL-based SignatureValidator

- src/inc/internal/Applicability.hpp
- src/msix/unpack/ApplicabilityCommon.cpp
- src/msix/unpack/AppxBundleManifest.cpp
**ISSUE :** https://github.com/microsoft/msix-packaging/issues/516
**ROOT CAUSE :** 
In "AppxBundleManifest.xml" of "WindowsTerminal.msixbundle", there are pseudo locales present in "Resource" tag.
Parsing of AppxBundleManifest.xml file is failing during unpack because of above mentioned pseudo locales as the max length limit for "Region" in "Language" is set to 4 and length of "Region" in pseudo locales "QPS-PLOCA" and "QPS-PLOCM" is 5.
**FIX :**
Allow pseudo locales in constructor of class "Bcp47Tag" by using a flag "allowPseudoLocale". So, when "AppxBundleManifest.xml" is parsed in "AppxBundleManifest.cpp", "allowPseudoLocale" is passed as "true" in constructor of class "Bcp47Tag".
> Add logic to allow pseudo locales in AppxBundleManifest.xml file of .msixbundle packages

- sample/PackSample/PackSample.cpp
It looks like earlier, this was depending on one of the headers it imports to import <memory> to provide unique_ptr; however, this is not necessarily the case, so it needs to be explicitly imported.
> Explicitly import <memory> in PackSample.cpp

- lib/catch2/catch.hpp
- src/test/msixtest/CMakeLists.txt
This rolls to the release available at
https://github.com/catchorg/Catch2/releases/tag/v2.13.10, and notably picks up a fix for non-constexpr MINSIGSTKSZ, which can break builds on Linux, as discussed in https://github.com/catchorg/Catch2/issues/2421.
> Roll Catch2 to 2.13.10

- MsixCore/msixmgr/msixmgr.cpp
- What issue your PR is related to.
Make vhdSize argument as optional for unpack command. When vhdSize will not be provided, 4x of source package size in MB will be used as recommended size of vhd.
- What change your PR adds.
Logic to check if vhdSize is not provided and then calculating the recommended vhdSize.
- How you tested your change.
Checked for a bunch of apps, what is the minimum vhdSize that those apps were able to get unpacked with and local app attach was working for them. Outcome of this exercise was recommended vhdSize, which came out to be 4x of source package size in MB.
After adding the logic to code, tested the vhdSize creation flow for a bunch of apps.
> [Task-43591819] - Add logic to use recommended vhdSize when vhdSize is not provided by user

- MsixCore/msixmgrLib/msixmgrLib.vcxproj
Rapid json headers files could not be detected as the include file path was missing in AdditionalIncludeDirectories.
> Fixed debug build errors while running from Visual studio for msixmgr project

- tools/pipelines-tasks/AppInstallerFile/package-lock.json
- tools/pipelines-tasks/AppInstallerFile/package.json
- tools/pipelines-tasks/MsixAppAttach/package-lock.json
- tools/pipelines-tasks/MsixAppAttach/package.json
- tools/pipelines-tasks/MsixPackaging/package-lock.json
- tools/pipelines-tasks/MsixPackaging/package.json
- tools/pipelines-tasks/MsixSigning/package-lock.json
- tools/pipelines-tasks/MsixSigning/package.json
- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
- tools/pipelines-tasks/azure-pipelines/templates/build-steps.yml
- tools/pipelines-tasks/common/package-lock.json
- tools/pipelines-tasks/common/package.json
- tools/pipelines-tasks/package-lock.json
- tools/pipelines-tasks/package.json
This PR does three things for the AzDO pipeline tasks extension:
* Update all the npm dependencies to the latest
* Update the code analysis tasks used in the pipelines to the current major version as the previous ones are deprecated
* Add a required SBOM validation task, and set the SBOM generation to only consider the tasks project
> [AzDO extension] Update tasks dependencies, code analysis tasks and add SBOM validation

- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
ESRP code signing failure with current ESRP codesigning task version 1.0.
The .NET dependencies installed on the agent machine do not match with the .NET dependencies required for ESRP codesigning earlier task version. 
ESRP Code signing task version is changed to 4.0
Verified ESRP code signing task.
> Update ESRP Codesigning task version in ado pipelines

- tools/pipelines-tasks/PublishForTesting.ps1
- tools/pipelines-tasks/azure-pipelines/.gdnbaselines
- tools/pipelines-tasks/azure-pipelines/.gdnsuppress
- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
- tools/pipelines-tasks/build.ps1
- tools/pipelines-tasks/package-lock.json
- tools/pipelines-tasks/package.json
- tools/pipelines-tasks/test/mock-tests/signing-with-base64-cert-success.ts
This change is being made to migrate our pipeline to 1ES Pipeline Template (1ESPT). This is necessary to comply with new requirements and ensure that it is part of a governed solution.
- Updated pipeline yaml file as per 1ES Pipeline Template format (1ESPT)
- Added .gdnbaselines and .gdnsuppress files for generating baselines and suppressions  
- Made changes in code to fix violations (Credscan, PSScriptAnalyzer, etc) that were causing build errors in the migrated pipeline.
Tested the pipeline by running the build for this branch. The pipeline was verified to be running successfully and all tasks were completing without errors.
> Migrating pipeline to 1ES Pipeline Template (1ESPT)

- src/inc/internal/ZipObjectWriter.hpp
- src/msix/pack/ZipObjectWriter.cpp
This commit resolves issue #619 by ensuring that the central directory in .appx files created by makemsix.exe is sorted in the same order as MakeAppx.exe. The fix involves tracking the sequence of file names during the creation of the zip file and sorting the central directory entries accordingly before writing them to the stream.
- Add a vector to track the sequence of file names in ZipObjectWriter.
- Sort central directory entries based on the tracked file name sequence before writing them to the zip file.
Resolves: #619
This was tested building via `makewin.cmd x64 --debug --pack`. 
The following files
[test_makemsix.zip](https://github.com/microsoft/msix-packaging/files/14545644/test_makemsix.zip)
were packed with:
`.vs\bin\makemsix pack -d C:\test_makemsix -p …
> Fix inconsistent zip structure in .appx files created by makemsix.exe

- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
- tools/pipelines-tasks/azure-pipelines/ci-build.yml
- tools/pipelines-tasks/azure-pipelines/templates/build-steps.yml
**Why is this change being made?**
As the current ADO project is getting decommissioned, the existing msix-packaging pipelines of that project need to be migrated to a new ADO project. 
**What changed?**
- Updated `tools/pipelines-tasks/azure-pipelines/build-vsix.yml` for ESRP Code Signing
- Migrated `msix-packaging AzDO tasks CI` pipeline to 1ESPT
- Remove deprecated Semmle  Guardin Task from `tools/pipelines-tasks/azure-pipelines/templates/build-steps.yml`
**How was the change tested?**
Tested the pipeline by running the build for this branch.
> Migration of Azure Pipelines
