- src/msix/CMakeLists.txt
Remove VS_WINRT_COMPONENT to allow building this project using CMake's Visual Studio Generators
> Fix issue using CMake's Visual Studio Generators

- README.md
- cmake/crypto_sources.cmake
- makeios.sh
- makemac.sh
- pipelines/azure-pipelines-ios.yml
- pipelines/azure-pipelines-macos.yml
- test/MacOS-Linux/testios.sh
Build release emulator and arm64 and debug emulator binaries for iOS using Azure Pipelines. Builds are executed automatically for every PR to master and when PRs are completed to master.
Removed unnecessary openssl files.
> Setup pipelines ios

- src/inc/AppxPackaging.hpp
Add IAppxPackageWriter, IAppxPackageWriter3 and its utf8 variants to AppxPackaging.hpp
> Add IAppxPackageWriter, IAppxPackageWriter3 and its utf8 variants

- src/inc/AppxPackageObject.hpp
- src/inc/AppxPackaging.hpp
- src/inc/DirectoryObject.hpp
- src/inc/MsixFeatureSelector.hpp
- src/inc/StorageObject.hpp
- src/inc/ZipObject.hpp
- src/makemsix/CMakeLists.txt
- src/makemsix/main.cpp
- src/msix/CMakeLists.txt
- src/msix/PAL/FileSystem/POSIX/DirectoryObject.cpp
- src/msix/PAL/FileSystem/Win32/DirectoryObject.cpp
- src/msix/common/AppxFactory.cpp
- src/msix/msix.cpp
- src/msix/unpack/AppxPackageObject.cpp
1. Add new entrypoint PackPackage.
2. Add new pack option to makemsix.
3. Remove unnecesary methods from IStorageObject that were not implemented in most objects that 
4. implement that interface.
5. Create new IDirectoryObject interface and get files and last modified dates from files in a given directory.
Next will be the basics of the package writer object
> New pack entrypoint and get files from a given directory

- preview/Win7Msix/Win7MSIXInstaller/ValidateTargetDeviceFamily.cpp
- preview/Win7Msix/Win7MSIXInstaller/ValidateTargetDeviceFamily.hpp
- preview/Win7Msix/Win7MSIXInstallerLib/Win7MSIXInstallerLib.vcxproj
Fix incomplete merge of lib splitting with validatetargetdevicefamily checkin.
> merge in validatetargetdevicefamily and update namespace

- src/msix/unpack/AppxPackageObject.cpp
Fixing merge conflict in packaging branch
> Fix merge conflict

- sample/BundleSample/BundleSample.cpp
- sample/BundleSample/CMakeLists.txt
- sample/CMakeLists.txt
- sample/ExtractContentsSample/CMakeLists.txt
- sample/ExtractContentsSample/ExtractContentsSample.cpp
- sample/OverrideLanguageSample/CMakeLists.txt
- sample/OverrideLanguageSample/OverrideLanguageSample.cpp
- sample/OverrideStreamSample/CMakeLists.txt
- sample/OverrideStreamSample/OverrideStreamSample.cpp
- sample/PackSample/CMakeLists.txt
- sample/PackSample/PackSample.cpp
- sample/inc/Helpers.hpp
- src/inc/MSIXWindows.hpp
- src/makemsix/main.cpp
- src/msix/pack/AppxPackageWriter.cpp
Create PackSample under samples to show how to use the AppxPackaging APIs to build a package. 
The sample takes a directory and the name of the package to create. AppxManifest.xml is required to be in the directory.
Refactor samples and create a Helper.hpp header
> Packaging sample

- CMakeLists.txt
- makeaosp.sh
- makeios.sh
- pipelines/azure-pipelines-aosp.yml
- pipelines/azure-pipelines-ios.yml
- src/msix/CMakeLists.txt
Pack is not supported for mobile devices.
> Disable pack for mobile

- CODEOWNERS
- README.md
Add git-lfs to pre-requisisites section of Readme.
> Update Readme.md and CODEOWNERS

- preview/MsixCore/MsixMgrWix/MsixMgrWix.wixproj
- preview/MsixCore/MsixMgrWix/Product.wxs
Switch casing to all lower (msixmgr) in user facing elements. 
Set PATH environment variable so msixmgr can be launched from cmdline from any folder.
> update casing to msixmgr, set path environment for launching cmdline

- preview/MsixCore/msixmgr/msixmgr.rc
Added the file version 1.0.0.0 to msixmgr.exe binary.
> Added fileversion to msixmgr binary

- preview/MsixCore/Tests/MsixCoreTest/MsixCoreTest.cpp
- preview/MsixCore/Tests/MsixCoreTest/MsixCoreTest.hpp
- preview/MsixCore/Tests/notepadplusCopy.msix
- Fix existing tests
- Added tests for shared binaries
> Tests for shared binaries

- preview/MsixCore/msixmgr/InstallUI.cpp
- preview/MsixCore/msixmgr/msixmgr.rc
- preview/MsixCore/msixmgr/resource.h
Created new branch based off of from https://github.com/microsoft/msix-packaging/pull/242 with feedback from code review comments. Manually edited resource files to include new strings.
Split up WXS error string to 2 parts to account for the app name.
> Added Loc Strings

- preview/MsixCore/Tests/JavaPSFexample.appx
- preview/MsixCore/Tests/test.ps1
- preview/MsixCore/msixmgr/Extractor.cpp
- preview/MsixCore/msixmgr/InstallUI.cpp
- preview/MsixCore/msixmgr/MsixRequest.cpp
- preview/MsixCore/msixmgr/PSFScriptExecuter.cpp
- preview/MsixCore/msixmgr/PSFScriptExecuter.hpp
- preview/MsixCore/msixmgr/Package.cpp
- preview/MsixCore/msixmgr/Package.hpp
- preview/MsixCore/msixmgr/StartMenuLink.cpp
- preview/MsixCore/msixmgr/StartMenuLink.hpp
- preview/MsixCore/msixmgrLib/inc/IPackage.hpp
- preview/MsixCore/msixmgrLib/msixmgrLib.vcxproj
Adding support for PSF commandline arguments, working directory, and runonce=true startscript script execution during the install.
> Psf handler

- preview/MsixCore/msixmgrLib/cgmanifest.json
- preview/MsixCore/msixmgrLib/msixmgrLib.vcxproj
Creating manual json file to check if task will detect component.
> Creating manual json file to test

- preview/MsixCore/MsixMgrWix/MsixMgrWix.wixproj
- preview/MsixCore/MsixMgrWix/Product.wxs
- preview/MsixCore/MsixMgrWix/WiSubStg.vbs
- preview/MsixCore/MsixMgrWix/de-de.wxl
- preview/MsixCore/MsixMgrWix/en-us.wxl
- preview/MsixCore/MsixMgrWix/es-es.wxl
- preview/MsixCore/MsixMgrWix/fr-fr.wxl
- preview/MsixCore/MsixMgrWix/it-it.wxl
- preview/MsixCore/MsixMgrWix/ja-jp.wxl
- preview/MsixCore/MsixMgrWix/ko-kr.wxl
- preview/MsixCore/MsixMgrWix/postbuild.ps1
- preview/MsixCore/MsixMgrWix/pt-pt.wxl
- preview/MsixCore/MsixMgrWix/ru-ru.wxl
- preview/MsixCore/MsixMgrWix/zh-cn.wxl
- preview/MsixCore/MsixMgrWix/zh-tw.wxl
Break out localizable strings into separate wxl files for the languages we support,
Add postbuild script to create transforms and embed the transforms into one multilingual .msi package.
> Add wix localization

- preview/MsixCore/msixmgrLib/resourceConfig.rcconfig.xml
Added rcconfig.xml file which generates a mui file and a language neutral file locally. This change has been committed in order to receive mui files back from api.
> Add rcconfig.xml file for mui

- preview/MsixCore/msixmgr/msixmgr.vcxproj
Update postbuild event script to,
- Run muirct.exe to generate language neutral and mui file for English.
- Copy msixmgr.exe to msixmgrOriginal.exe
- Copy msixmgr_LN.exe to msixmgr.exe
- Delete msixmgr_LN .exe
> Update postbuild event script

- preview/MsixCore/MsixMgrWix/LocalizedFiles.wxs
- preview/MsixCore/MsixMgrWix/MsixMgrWix.wixproj
- preview/MsixCore/MsixMgrWix/Product.wxs
- preview/MsixCore/MsixMgrWix/postbuild.ps1
Ran heat.exe to generate LocalizedFiles.wxs file. Included this wxs file in Product.wxs and wixproj file. This creates msi for all the languages. Creating PR for review.
> Add heat directory to embed mui files into msi

- MsixCore/MsixMgrWix/Product.wxs
- MsixCore/MsixMgrWix/de-de/strings.wxl
- MsixCore/MsixMgrWix/en-us/strings.wxl
- MsixCore/MsixMgrWix/es-es/strings.wxl
- MsixCore/MsixMgrWix/fr-fr/strings.wxl
- MsixCore/MsixMgrWix/it-it/strings.wxl
- MsixCore/MsixMgrWix/ja-jp/strings.wxl
- MsixCore/MsixMgrWix/ko-kr/strings.wxl
- MsixCore/MsixMgrWix/pt-pt/strings.wxl
- MsixCore/MsixMgrWix/ru-ru/strings.wxl
- MsixCore/MsixMgrWix/zh-cn/strings.wxl
- MsixCore/MsixMgrWix/zh-tw/strings.wxl
Block the x86 msi from installing on x64.
> Block x86 msi on x64

- MsixCore/msixmgr/InstallUI.cpp
Moved the progress down, moved the displaypercent window down and also made this wider so that it fits the appended text.
> Progress bar updates

- tools/utils/Utils/ProcessRunner/DesktopProcessRunner.cs
- tools/utils/Utils/ProcessRunner/ProcessRunnerBase.cs
- tools/utils/UtilsTests/LoggerTests/LoggerCustomProviderTests.cs
DesktopProcessRunner.cs doesn't allow the caller to specify the working directory. This change enable that functionality
> MSIX Utils

- SUPPORT.md
> Add SUPPORT.MD

- src/msix/PAL/Signature/Win32/SignatureValidator.cpp
- src/test/msixtest/unpack.cpp
Add a call to WinVerifyTrust to validate Timestamp on msix package.
> Validate timestamp in Windows

- src/msix/PAL/XML/xerces-c/XmlObject.cpp
Prevent XXE based on new recommendation by OWASP/CheatSheetSeries#353
Resolves #481
> Prevent XXE attacks

- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
Add generation of SBoM manifest to the AzDO extension as required for compliance.
> Add SBoM manifest generation

- tools/pipelines-tasks/AVDAppAttachPublish/PublishAVD.ps1
- tools/pipelines-tasks/AVDAppAttachPublish/main.ts
---
<br>
<details open>
<summary><b>Why were the changes made? </b></summary>
- The current avdpublish-task is not having real time logging functionality.
- It was dumping the logs after the entire execution completes, leading to a non-user-friendly experience.
</details>
<br>
---
<br>
<details open>
<summary><b>What files & flows were changed? </b></summary>
- The `main.ts1` was updated to pass the full path to the `AppAttachKernel` DLLs.
- The `main.ts1` was updated to remove the log dumping logic.
- The `main.ts1` was updated to make the execute function asynchronous.
- The `AVDPublish.ps1` was updated to implement the `IMessageHandler` interface.
</details>
<br>
---
<details open>
<summary><b>How were the changes tested? </b></summary>
- Tested the pipeline by running the build for …
> [Task 48751920] Added IMessageHandler implementation in PS Script for logging in avdpublish-task

- tools/pipelines-tasks/azure-pipelines/build-vsix.yml
updating pipeline to validate ESRP code signing
> Update build-vsix.yml for Azure Pipelines
